### ISSUE TITLE
Conflicting dependencies between `aind-data-schema` and `aind-data-transfer-models`

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/aind-data-transfer-models#18]
When trying to install the [watchdog service](https://github.com/AllenNeuralDynamics/aind-watchdog-service) with the latest version of aind-data-schema I got the following error when attempting to bootstrap the environment:

```plaintext
The conflict is caused by:
    aind-data-schema 0.38.5 depends on aind-data-schema-models>=0.1.7
    aind-data-transfer-models 0.5.1 depends on aind-data-schema-models==0.1.1
```

For reference, these are the versions I am specifying:
```
    'aind-watchdog-service@git+https://github.com/AllenNeuralDynamics/aind-watchdog-service@development',
    'aind-data-schema==0.38.5'
```

As of the date of this issue, the `development` branch targets [49092f2](https://github.com/AllenNeuralDynamics/aind-watchdog-service/commit/49092f270dbc675fc0e4fa028d6903ed6bf90407).

**Comment by jtyoung84** [comment]
I should be able to unpin aind-data-schema-models

**Comment by bruno-f-cruz** [comment]
Cool! Is there an ETA for this change? Trying to figure out if I should wait or try to come up with a temporary solution. Thanks!
