### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-data-transfer-models#46]
# User story
As a user, I want instructions on how to use this repository. 

# Acceptance criteria
- [ ] Migrate instructions on how to use the BasicUploadJobConfigs to generate a session from the aind-metadata-mapper docs to this repo

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined 
- [ ] 2. Team understands acceptance criteria 
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [ ] 4. Acceptance criteria is verifiable / testable 
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by jtyoung84** [comment]
This is done here: https://aind-data-transfer-service.readthedocs.io/en/latest/UserGuide.html#using-the-rest-api
